import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import NavbarRedesign from "./components/navbar/NavbarRedesign";
import Footer from "./components/navbar/Footer";
import Provider from "./lib/api/NextAuthProvider";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { ReactQueryClientProvider } from "./lib/api/ReactQueryProvider";
import Head from "next/head";
import LogoutConfirmation from "./components/message/LogoutConfirmation";
import { Toaster } from "sonner";
import Script from "next/script";
import GoogleAnalytics from "./lib/analytics/GoogleAnalytics";
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "K-Owl",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
      <GoogleAnalytics />
        <ReactQueryClientProvider>
          <Provider>
            {/* <Navbar /> */}
            <NavbarRedesign />
            <div className="pt-[50px] min-h-[83vh]">{children}</div>
          </Provider>
        </ReactQueryClientProvider>

        <LogoutConfirmation />
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
